Fix Arduino connection recovery not working
```
ERROR:afancontrol:Error in the Arduino connection watchdog thread
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/afancontrol/arduino.py", line 340, in _thread_run
    self._reader_thread.close()
  File "/usr/lib/python3/dist-packages/serial/threaded/__init__.py", line 224, in close
    self.stop()
  File "/usr/lib/python3/dist-packages/serial/threaded/__init__.py", line 176, in stop
    self.serial.cancel_read()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 509, in cancel_read
    os.write(self.pipe_abort_read_w, b"x")
TypeError: an integer is required (got type NoneType)
```